### ISSUE TITLE
Cleanup from pr #40

### ISSUE THREAD

**Issue by jonnyz32** [Mapepire-IBMi/mapepire-java#51]
![image](https://github.com/user-attachments/assets/85e406a6-1e6c-4756-b69f-9f2b7751acb5)
![image](https://github.com/user-attachments/assets/177b4c02-6099-4d21-9f45-b59f2a52a8ba)
![image](https://github.com/user-attachments/assets/873f6be9-e30e-4215-b764-d7eef1faa320)
![image](https://github.com/user-attachments/assets/7d1365df-3bfc-41c9-8af1-f98a5ba4fd7f)

**Comment by SanjulaGanepola** [comment]
TODO: Revert https://github.com/Mapepire-IBMi/mapepire-java/pull/52
